
services:
  backend:
    build :
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
